### ISSUE TITLE
header兼容性问题

### ISSUE THREAD

**Issue by c1230v** [mix-php/http-message#2]
[feat:http-message:移除header小写处理
](https://github.com/mix-php/http-message/commit/f0ab86b6da4b73f34569481f5019d5e24b4f5fd2)

昨天测试websocket，有遇到握手失败，经查看源码后发现是 Sec-WebSocket-* 的header未能读取到，在chrome里使用js连接ws服务器时，header里会有大小写同时使用的情况，不能确定是不是跟swoole版本(v4.7.0)也有关，但是依psr规范的话，http-message的实现应该内部有统一使用大小写，这时是不应该出现这类问题

从git上查看历史版本后发现在 `f0ab86b6da4b73f34569481f5019d5e24b4f5fd2` 版本时有移除header大小写处理，请review一下，确认移除大小写处理的必要性和正确性

**Comment by onanying** [comment]
@c1230v 我同步修改 websocket https://github.com/mix-php/websocket/commit/28d6a5c952722403a1e3ce92c9f89e399d4ceda7

**Comment by onanying** [comment]
composer update mix/websocket

**Comment by c1230v** [comment]
感谢，晚点我再测试一次

**Comment by c1230v** [comment]
查看您的修改，是将 sec-websocket-key 替换为 Sec-Websocket-Key，不过我这边查看到chrome的header name 是 Sec-WebSocket-Key，所以心灵运行的结果应该是问题还有存在，解决正途应该还是 http-message 内部使用统一的大小写规范

**Comment by onanying** [comment]
@c1230v 我有我的考虑，为了兼容fpm和workerman

**Comment by c1230v** [comment]
我英语有问题，刚才又去看了一下psr规范，getHeader 的param name 注释有说明，要求使用大小写敏感的header field name

@param string $name Case-insensitive header field name.

这个我可能得去再查一下websocket协议，有点记不清楚了，chrome使用Sec-WebSocket-Key，如果其他应用不规范，这里很容易出问题

**Comment by onanying** [comment]
@c1230v Sec-WebSocket-Key 是标准，但是 fpm 是全大写，workerman 的标准的 Sec-WebSocket-Key，mixphp v3 是支持3个平台的，必须要妥协，于是 fpm,swoole 就都是首字母大写，而 workerman 就是 Sec-WebSocket-Key 这种原始的，比如 fpm 的全大写，和 swoole 的全小写这种原始数据的不统一，导致你无法还原成本来的样子，现在这种妥协是没办法的，原始数据被改变了

**Comment by onanying** [comment]
编程世界总是有各种妥协，我也想问：为啥 fpm 要搞程全大写，为啥 sw 要搞成全小写，为何不按标准来？

**Comment by c1230v** [comment]
websocket协议 rfc6455 没有关于大小写的描述，示例是 Sec-WebSocket-Key
HTTP/2 协议 RFC7504 里规定要转为小写
HTTP/1.1 里是要求大小写敏感
psr 规范是大小写敏感

swoole里是把header field name全部使用小写

这个我再想办法处理吧，不行就拉一份fork给自己用了，这个总得找一个妥协，真是为难你了

**Comment by c1230v** [comment]
应该是我英文水平的问题，Case-insensitive 应该是说大小写不敏感，如果是我理解错的话，http-message统一使用大写或者小写应该是个出路

吐槽下百度翻译，Case-insensitive 同时给出了大小写敏感和大小写不敏感两种翻译，泪奔了

**Comment by onanying** [comment]
@c1230v 这个不影响 mix/websocket 的使用，我上一个commit已经修复了 ws 的握手

**Comment by c1230v** [comment]
好的，我下午找时间测一下，谢谢作者，辛苦

**Comment by onanying** [comment]
@c1230v 经过群里的讨论，为了兼容性统一修改为全部平台都为小写 https://github.com/mix-php/mix/commit/2509f59fe729f4621e0f520eaa196b252b7f831d
